type ActionType =
    "UPDATE_SELECTED_DATE" |
    "ADD_PEAK_FLOW" |
    "DELETE_PEAK_FLOW" |
    "UPDATE_PEAK_FLOW" |
    "ADD_RESCUE_TREATMENT_USE" |
    "DELETE_RESCUE_TREATMENT_USE" |
    "UPDATE_RESCUE_TREATMENT_USE" |
    "ADD_SYMPTOMS_RECORD" |
    "DELETE_SYMPTOMS_RECORD" |
    "UPDATE_SYMPTOMS_RECORD" |
    "ADD_SOLID_TREATMENT" |
    "DELETE_SOLID_TREATMENT" |
    "UPDATE_SOLID_TREATMENT";

export default ActionType;